# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Aplicar migraciones
        run: python manage.py migrate
      - name: Ejecutar aplicación
        run: python manage.py runserver

